language: python

python: 3.5

# Use container based infrastructure
sudo: false

addons:
  apt:
    packages:
      - libenchant-dev

env:
  global:
    # encrypted Sauce Labs sub-account user name
    - secure: RGXS2qmljsyLVGEifz9yvLwdg33KxPDeuwHx0QFmjSkQuJZP92Xxl36qr6rNel52L+39oya8BGD/ddB6RNI6R5TsoOvQGMlrVZmYy4d8EPA7J8u3+Mpp1zQGK1ACmcnVm+5h8dbHeWtZW/1SovnclUYem16KUmQf35l9G9tKc/I=
    # encrypted Sauce Labs sub-account token
    - secure: Lt1n+6a4hj7BuShOufWfiAF3aTC4B6xpHwwcbklVy+fdy4pkY3okXO9CFtWkOTBRrFrgc8R+PL9dZ6ObK3SE1w7LU3dur89uIvJ4RXQ1uROr40PXAxD8RO+/2wp7nhh6CmG7GEKpuKt5QHbgdFVrJtmyoPp4vco1pU86njtEico=
    # encrypted Code Climate token
    - secure: Jq2JBTBMYLpnrwk6uuAWGOX4y+TEVkBuwSZywSrlKb9sW77DloxRfGXH81Q9juvaAy4KqtcGY6HE5vqJSo77MS/cmbtmZe4ypPKgVFy2YDDUGdLi65vEjkerjAmtS7bYBVur+fWG0mpYAmnfj06d0MgkBgwgCr4yLbJFtW8ElAM=
  matrix:
    # Matrix-size reduction strategies:
    #   PY strategy: do not test 3.3 at all.
    #   DB stragegy: we use raw queries, so good coverage is required. Test on
    #                each django/cms combination.
    #   FE strategy: only test on Django/CMS3.3 combinations, but place tests on
    #                different Python ENVs if possible. Also, test against all
    #                DB backends
    # NOTE: MYSQL AND POSTGRES TESTS ARE DISABLED UNTIL #339 IS MERGED.
    - TOXENV=flake8
    - TOXENV=py35-dj19-sqlite-cms34
    - TOXENV=py35-dj19-sqlite-cms33-fe FE=1
    - TOXENV=py35-dj19-sqlite-cms32
    - TOXENV=py34-dj19-sqlite-cms34
    - TOXENV=py34-dj19-sqlite-cms33
    - TOXENV=py34-dj19-sqlite-cms32
    - TOXENV=py27-dj19-sqlite-cms34
    - TOXENV=py27-dj19-sqlite-cms33
    - TOXENV=py27-dj19-sqlite-cms32
    - TOXENV=py35-dj18-sqlite-cms34
    - TOXENV=py35-dj18-sqlite-cms33
    - TOXENV=py35-dj18-sqlite-cms32
    - TOXENV=py34-dj18-sqlite-cms34
    - TOXENV=py34-dj18-sqlite-cms33
    - TOXENV=py34-dj18-sqlite-cms32
    - TOXENV=py27-dj18-sqlite-cms34
    - TOXENV=py27-dj18-sqlite-cms33-fe FE=1
    - TOXENV=py27-dj18-sqlite-cms32
    - TOXENV=py34-dj17-sqlite-cms32
    - TOXENV=py33-dj17-sqlite-cms32
    - TOXENV=py27-dj17-sqlite-cms32
    - TOXENV=py33-dj16-sqlite-cms32
    - TOXENV=py27-dj16-sqlite-cms32
    - TOXENV=py26-dj16-sqlite-cms32

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

before_script:
  - if [ "$FE" == 1 ]; then nvm install 0.12.7 && nvm use 0.12.7; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g npm@2; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm install; fi

after_script:
  - codeclimate < tests/coverage/**/lcov.info

script:
  - tox -e $TOXENV

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
